id: I943C4150
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T14:25:44+00:00'
last_modified: '2022-06-07T12:04:21.257261+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12539
  title: ཕྱག་ཆེན་ལྔ་ལྡན་སོགས་ཀྱི་ཁྲིད་ཡིག་ཟབ་རྒྱས་རིན་ཆེན་ཕྲེང་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6E27:
      image_group_id: I1KG12570
      title: Volume 1 of phyag chen lnga ldan sogs kyi khrid yig zab rgyas rin chen
        phreng ba/
      total_pages: 258
      order: 1
      base_file: 6E27.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
